var fs = require("fs");
var dir = "I:/.codex_wecom/outputs/presentations/wecom-bot-intro/slides";
fs.mkdirSync(dir, { recursive: true });

var lines = [];
lines.push('import { Fragment, createRef } from "@oai/artifact-tool/presentation-jsx";');
lines.push("");
lines.push('var colors = { bg: "#0a0e17", bgCard: "#131a2b", bgLighter: "#1a2340", accent: "#4f8cff", accentDim: "#3451b2", green: "#22c55e", amber: "#f59e0b", red: "#ef4444", purple: "#a855f7", text: "#e2e8f0", textDim: "#94a3b8", textMuted: "#64748b", border: "#1e293b", white: "#ffffff" };');
lines.push('var fonts = { display: "Inter", body: "Inter", mono: "JetBrains Mono" };');
lines.push("");
lines.push('function gradientH(from, to) { return "linear-gradient(135deg, " + from + " 0%, " + to + " 100%)"; }');
lines.push("");
lines.push("// === Slide 1: Title ===");
lines.push("function SlideTitle() {");
lines.push('  return (');
lines.push('    <view width={1280} height={720} fill={colors.bg}>');
lines.push('      <view x={680} y={-100} width={700} height={920} fill={gradientH(colors.accent + "15", colors.purple + "10")} transform="rotate(15deg)" />');
lines.push('      <view x={100} y={160} width={700} fill="none">');
lines.push('        <textStyle fill={colors.accent} fontFamily={fonts.mono} fontSize={14} letterSpacing={4}>WECOM AI-BOT FRAMEWORK</textStyle>');
lines.push('        <textStyle fill={colors.white} fontFamily={fonts.display} fontSize={56} fontWeight={800} y={20}>企业微信智能机器人</textStyle>');
lines.push('        <textStyle fill={colors.white} fontFamily={fonts.display} fontSize={56} fontWeight={800} y={76}>应用框架</textStyle>');
lines.push('        <textStyle fill={colors.textDim} fontFamily={fonts.body} fontSize={18} y={100}>42 原子技能 + 5 组合技能 + 多 Bot 管理</textStyle>');
lines.push("      </view>");
lines.push('      <view x={100} y={440} width={900} fill="none" flexDirection="row" gap={20}>');
lines.push('        <view width={200} height={80} fill={colors.bgCard} borderRadius={8} padding={16} border={"1 solid " + colors.border}>');
lines.push('          <textStyle fill={colors.accent} fontFamily={fonts.display} fontSize={32} fontWeight={800}>57</textStyle>');
lines.push('          <textStyle fill={colors.textDim} fontFamily={fonts.body} fontSize={12} y={4}>TypeScript 文件</textStyle>');
lines.push("        </view>");
lines.push('        <view width={200} height={80} fill={colors.bgCard} borderRadius={8} padding={16} border={"1 solid " + colors.border}>');
lines.push('          <textStyle fill={colors.green} fontFamily={fonts.display} fontSize={32} fontWeight={800}>17</textStyle>');
lines.push('          <textStyle fill={colors.textDim} fontFamily={fonts.body} fontSize={12} y={4}>单元测试 100%</textStyle>');
lines.push("        </view>");
lines.push('        <view width={200} height={80} fill={colors.bgCard} borderRadius={8} padding={16} border={"1 solid " + colors.border}>');
lines.push('          <textStyle fill={colors.purple} fontFamily={fonts.display} fontSize={32} fontWeight={800}>42+5</textStyle>');
lines.push('          <textStyle fill={colors.textDim} fontFamily={fonts.body} fontSize={12} y={4}>原子+组合 Skill</textStyle>');
lines.push("        </view>");
lines.push('        <view width={200} height={80} fill={colors.bgCard} borderRadius={8} padding={16} border={"1 solid " + colors.border}>');
lines.push('          <textStyle fill={colors.amber} fontFamily={fonts.display} fontSize={32} fontWeight={800}>3</textStyle>');
lines.push('          <textStyle fill={colors.textDim} fontFamily={fonts.body} fontSize={12} y={4}>Bot 示例就绪</textStyle>');
lines.push("        </view>");
lines.push("      </view>");
lines.push('      <view x={100} y={620} fill="none"><textStyle fill={colors.textMuted} fontFamily={fonts.mono} fontSize={11}>v1.3 · I:/.codex_wecom</textStyle></view>');
lines.push("    </view>");
lines.push("  );");
lines.push("}");
lines.push("");
lines.push("exports.default = {");
lines.push("  slides: [SlideTitle],");
lines.push('  metadata: { title: "WeCom AI-Bot Framework", slideWidth: 1280, slideHeight: 720 }');
lines.push("};");

fs.writeFileSync(dir + "/deck.jsx", lines.join("\n"));
console.log("Wrote " + lines.length + " lines to deck.jsx");
